# Generated by Django 4.1.7 on 2023-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite",
            name="date",
            field=models.BigIntegerField(default=1680265608),
        ),
        migrations.AlterField(
            model_name="session",
            name="date",
            field=models.BigIntegerField(default=1680265608),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=64, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="login",
            field=models.CharField(max_length=20, unique=True, verbose_name="Логин"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=64, verbose_name="Пароль"),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.BigIntegerField(default=1680265608),
        ),
    ]
