# Generated by Django 4.1.7 on 2023-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_favourite_date_alter_session_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(null=True, upload_to="cars/"),
        ),
        migrations.AlterField(
            model_name="favourite",
            name="date",
            field=models.BigIntegerField(default=1680708794),
        ),
        migrations.AlterField(
            model_name="session",
            name="date",
            field=models.BigIntegerField(default=1680708794),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.BigIntegerField(default=1680708794),
        ),
    ]
